on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'terraform/**'
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read 

name: iac-gitops-terraform

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: terraform version
      # - uses: aws-actions/configure-aws-credentials@v4.1.0
      #   with:
      #     aws-region: "eu-central-1"
      #     role-to-assume: "arn:aws:iam::050451357127:role/github-oidc-assume-iac-role"